import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronLeft, Share, Download, FileText, X, Copy, Mail, Link2 } from 'lucide-react';
import { SpeedaLogo, InstagramLogo, TikTokLogo, SnapchatLogo, FacebookLogo } from '../components/PlatformLogos';
import { toast } from 'sonner';
import { jsPDF } from 'jspdf';

interface WeeklyReportScreenProps {
  onBack: () => void;
  onNavigate?: (screen: string) => void;
}

export const WeeklyReportScreen = ({ onBack, onNavigate }: WeeklyReportScreenProps) => {
  const [exportStep, setExportStep] = useState<'idle' | 'loading' | 'done'>('idle');

  const metrics = [
    { icon: '👁️', label: 'Total Reach', value: '28.3K', change: '↑ 23%' },
    { icon: '💜', label: 'Engagement', value: '5.1%', change: '↑ 12%' },
    { icon: '🛒', label: 'Conversions', value: '187', change: '↑ 31%' },
    { icon: '💰', label: 'Ad Spend', value: 'SAR 850', change: '↔ same' },
  ];

  const contentPerf = [
    { title: 'Chicken Shawarma Reel', eng: 8.2, w: '100%' },
    { title: 'Kitchen Behind Scenes', eng: 6.5, w: '79%' },
    { title: 'Weekend Special', eng: 4.1, w: '50%' },
    { title: 'Customer Review', eng: 3.8, w: '46%' },
  ];

  const platformStats = [
    { Logo: InstagramLogo, name: 'Instagram', followers: '+340', posts: 8, eng: '5.2%', best: 'Shawarma Reel' },
    { Logo: TikTokLogo, name: 'TikTok', followers: '+520', posts: 4, eng: '7.8%', best: 'Kitchen BTS' },
    { Logo: SnapchatLogo, name: 'Snapchat', followers: '+120', posts: 3, eng: '3.4%', best: '' },
    { Logo: FacebookLogo, name: 'Facebook', followers: '+85', posts: 4, eng: '2.1%', best: '' },
  ];

  const handleExportPDF = () => {
    setExportStep('loading');
    setTimeout(() => setExportStep('done'), 2000);
  };

  const downloadPDF = () => {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const pw = 210;
    const mx = 20;
    const blue: [number, number, number] = [0, 32, 212];
    const dark: [number, number, number] = [26, 26, 46];
    const gray: [number, number, number] = [107, 114, 128];

    // Page 1 - Cover & Summary
    doc.setFillColor(248, 246, 253);
    doc.rect(0, 0, pw, 297, 'F');

    doc.setFontSize(28);
    doc.setTextColor(dark[0], dark[1], dark[2]);
    doc.setFont('helvetica', 'bold');
    doc.text('Weekly Performance Report', pw / 2, 50, { align: 'center' });

    doc.setFontSize(14);
    doc.setTextColor(gray[0], gray[1], gray[2]);
    doc.text("Malek's Kitchen — Riyadh", pw / 2, 62, { align: 'center' });
    doc.text('March 12 — March 19, 2026', pw / 2, 72, { align: 'center' });

    // Executive Summary
    doc.setFillColor(blue[0], blue[1], blue[2]);
    doc.roundedRect(mx, 85, pw - mx * 2, 45, 4, 4, 'F');
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('AI EXECUTIVE SUMMARY', mx + 8, 96);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    const summaryLines = doc.splitTextToSize(
      'This was a strong week for your business. Engagement increased 23% driven by your Chicken Shawarma Reel. Your Ramadan campaign is performing above projections with a 2.8x ROAS. I recommend increasing TikTok investment next week.',
      pw - mx * 2 - 16
    );
    doc.text(summaryLines, mx + 8, 106);

    // Key Metrics
    doc.setTextColor(dark[0], dark[1], dark[2]);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text('Key Metrics', mx, 150);

    metrics.forEach((m, i) => {
      const x = mx + (i % 2) * 85;
      const y = 158 + Math.floor(i / 2) * 30;
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(x, y, 80, 25, 3, 3, 'F');
      doc.setFontSize(18);
      doc.setTextColor(dark[0], dark[1], dark[2]);
      doc.text(m.value, x + 5, y + 12);
      doc.setFontSize(9);
      doc.setTextColor(gray[0], gray[1], gray[2]);
      doc.text(m.label, x + 5, y + 20);
      doc.setTextColor(0, 150, 100);
      doc.text(m.change, x + 55, y + 12);
    });

    // Content Performance
    doc.setTextColor(dark[0], dark[1], dark[2]);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text('Content Performance', mx, 230);

    contentPerf.forEach((c, i) => {
      const y = 238 + i * 12;
      doc.setFontSize(10);
      doc.setTextColor(dark[0], dark[1], dark[2]);
      doc.text(c.title, mx, y);
      doc.text(`${c.eng}%`, pw - mx, y, { align: 'right' });
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(gray[0], gray[1], gray[2]);
    doc.text('Generated by Speeda AI — speeda.ai', pw / 2, 287, { align: 'center' });

    // Download
    doc.save('Speeda-Weekly-Report-March-2026.pdf');
    toast.success('PDF downloaded ✓');
  };

  const handleDownload = () => {
    downloadPDF();
    setExportStep('idle');
  };

  return (
    <motion.div initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} className="bg-background min-h-screen pb-8">
      <div className="px-5 pt-6">
        <div className="flex items-center gap-3 mb-1">
          <button onClick={onBack}><ChevronLeft size={24} className="text-foreground rtl:rotate-180" /></button>
          <h1 className="text-[20px] font-bold text-foreground flex-1">Weekly AI Report</h1>
          <button onClick={handleExportPDF} className="h-9 px-3 rounded-xl border border-border flex items-center gap-1 text-brand-blue text-[12px] font-bold"><Share size={14} /> Share</button>
        </div>
        <p className="text-[13px] text-muted-foreground ms-9">March 12 — March 19, 2026</p>

        {/* Cover */}
        <div className="mt-6 text-center">
          <div className="flex justify-center"><SpeedaLogo size={60} /></div>
          <h2 className="text-[24px] font-extrabold text-foreground mt-3">Weekly Performance Report</h2>
          <p className="text-[14px] text-muted-foreground mt-1">Malek's Kitchen — Riyadh</p>
          <p className="text-[12px] text-muted-foreground mt-0.5">Generated by Speeda AI on March 19, 2026</p>
          <div className="h-px bg-border mt-4" />
        </div>

        {/* Executive Summary */}
        <div className="mt-5 gradient-hero rounded-2xl p-5 text-primary-foreground">
          <p className="text-[11px] uppercase font-bold tracking-[1px] text-primary-foreground/70">✦ AI Executive Summary</p>
          <p className="text-[14px] leading-[1.6] mt-2">This was a strong week for your business. Engagement increased 23% driven by your Chicken Shawarma Reel which went semi-viral on Instagram. Your Ramadan campaign is performing above projections with a 2.8x ROAS. I recommend increasing TikTok investment next week based on your audience growth there.</p>
        </div>

        {/* Key Metrics */}
        <h3 className="text-[18px] font-bold text-foreground mt-6">Key Metrics</h3>
        <div className="grid grid-cols-2 gap-3 mt-3">
          {metrics.map((m, i) => (
            <div key={i} className="bg-card rounded-2xl p-4 border border-border-light">
              <span className="text-lg">{m.icon}</span>
              <p className="text-[20px] font-extrabold text-foreground mt-1">{m.value}</p>
              <div className="flex items-center justify-between mt-1">
                <span className="text-[11px] text-muted-foreground">{m.label}</span>
                <span className="text-[11px] font-bold text-green-accent">{m.change}</span>
              </div>
            </div>
          ))}
        </div>

        {/* Content Performance */}
        <h3 className="text-[18px] font-bold text-foreground mt-6">Content Performance</h3>
        <div className="bg-card rounded-2xl p-4 border border-border-light mt-3 space-y-3">
          {contentPerf.map((c, i) => (
            <div key={i}>
              <div className="flex justify-between text-[12px] mb-1">
                <span className="text-foreground font-medium">{c.title}</span>
                <span className="font-bold text-foreground">{c.eng}%</span>
              </div>
              <div className="h-2 rounded-full bg-muted overflow-hidden">
                <motion.div initial={{ width: 0 }} animate={{ width: c.w }} transition={{ duration: 0.8, delay: i * 0.1 }} className="h-full rounded-full gradient-hero" />
              </div>
            </div>
          ))}
          <p className="text-[12px] text-green-accent font-semibold mt-2">Best performing: Chicken Shawarma Reel (Instagram) — 12.4K reach, 1,234 likes</p>
        </div>

        {/* Platform Analysis */}
        <h3 className="text-[18px] font-bold text-foreground mt-6">Platform Performance</h3>
        <div className="mt-3 space-y-2">
          {platformStats.map((p, i) => (
            <div key={i} className="bg-card rounded-2xl p-4 border border-border-light flex items-center gap-3">
              <p.Logo size={24} />
              <div className="flex-1">
                <p className="text-[14px] font-semibold text-foreground">{p.name}</p>
                <p className="text-[11px] text-muted-foreground">{p.followers} followers · {p.posts} posts · {p.eng} avg eng</p>
                {p.best && <p className="text-[11px] text-green-accent font-medium">Best: {p.best}</p>}
              </div>
            </div>
          ))}
        </div>

        {/* Campaign Results */}
        <h3 className="text-[18px] font-bold text-foreground mt-6">Active Campaigns</h3>
        <div className="mt-3 space-y-2">
          {[
            { name: 'Ramadan Special', budget: '2,000', spent: '1,340', reach: '45.2K', roas: '2.8x', status: 'On Track ✅' },
            { name: 'Weekend Brunch', budget: '800', spent: '520', reach: '18.7K', roas: '2.1x', status: 'Completed ✅' },
          ].map((c, i) => (
            <div key={i} className="bg-card rounded-2xl p-4 border border-border-light">
              <p className="text-[14px] font-bold text-foreground">{c.name}</p>
              <div className="grid grid-cols-4 gap-2 mt-2">
                {[{ l: 'Budget', v: c.budget }, { l: 'Spent', v: c.spent }, { l: 'Reach', v: c.reach }, { l: 'ROAS', v: c.roas }].map((m, j) => (
                  <div key={j}><span className="text-[9px] uppercase text-muted-foreground font-semibold">{m.l}</span><p className="text-[13px] font-bold text-foreground">{m.v}</p></div>
                ))}
              </div>
              <span className="text-[11px] text-green-accent font-semibold mt-1 block">{c.status}</span>
            </div>
          ))}
        </div>

        {/* AI Actions */}
        <h3 className="text-[18px] font-bold text-foreground mt-6">What Speeda AI did for you</h3>
        <div className="bg-card rounded-2xl p-4 border border-border-light mt-3 space-y-2">
          {[
            'Published 12 posts across 4 platforms',
            'Responded to 23 comments and DMs automatically',
            'Optimized campaign budgets 3 times',
            'Boosted 2 high-performing posts',
            'Generated and scheduled next week\'s content plan',
            'Paused 1 underperforming ad (saved SAR 120)',
          ].map((a, i) => (
            <p key={i} className="text-[13px] text-foreground">✦ {a}</p>
          ))}
        </div>

        {/* Recommendations */}
        <h3 className="text-[18px] font-bold text-foreground mt-6">✦ AI Recommendations</h3>
        <div className="mt-3 space-y-2">
          {[
            { text: 'Increase TikTok posting frequency — your audience grew 18% there', cta: 'Create TikTok Plan →', nav: 'create' },
            { text: 'Prepare Eid Al-Fitr content — 3 weeks away', cta: 'Generate Eid Plan →', nav: 'create' },
            { text: 'Boost your Shawarma Reel on Instagram — est. 50K additional reach', cta: 'Boost Now →', nav: 'campaigns' },
          ].map((r, i) => (
            <div key={i} className="bg-card rounded-2xl p-4 border border-border-light border-l-4 border-l-purple">
              <p className="text-[13px] text-foreground">{r.text}</p>
              <button onClick={() => onNavigate?.(r.nav)} className="text-brand-blue text-[12px] font-bold mt-1">{r.cta}</button>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-8 text-center border-t border-border pt-5">
          <p className="text-[12px] text-muted-foreground">This report was automatically generated by Speeda AI</p>
          <div className="flex justify-center mt-2"><SpeedaLogo size={32} /></div>
          <p className="text-[12px] text-brand-blue font-medium mt-1">speeda.ai</p>
        </div>

        <button onClick={handleExportPDF} className="w-full h-[48px] rounded-2xl border border-border text-foreground text-[14px] font-bold btn-press mt-4 flex items-center justify-center gap-2">
          <Download size={16} /> Download PDF
        </button>
      </div>

      {/* Export PDF Modal */}
      <AnimatePresence>
        {exportStep !== 'idle' && (
          <>
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setExportStep('idle')} className="fixed inset-0 bg-foreground/30 z-50" />
            <motion.div initial={{ y: '100%' }} animate={{ y: 0 }} exit={{ y: '100%' }}
              className="fixed inset-x-0 bottom-0 z-50 bg-card rounded-t-3xl p-6">
              <div className="mx-auto mb-4 h-1.5 w-12 rounded-full bg-muted" />
              {exportStep === 'loading' ? (
                <div className="text-center py-8">
                  <motion.div animate={{ rotate: 360 }} transition={{ duration: 1, repeat: Infinity }} className="text-3xl inline-block">✦</motion.div>
                  <p className="text-[16px] font-bold text-foreground mt-4">Generating PDF report...</p>
                  <p className="text-[13px] text-muted-foreground mt-1">Including charts, metrics, and AI insights</p>
                  <div className="mt-4 h-2 rounded-full bg-muted overflow-hidden max-w-[200px] mx-auto">
                    <motion.div initial={{ width: 0 }} animate={{ width: '100%' }} transition={{ duration: 2 }} className="h-full gradient-btn rounded-full" />
                  </div>
                </div>
              ) : (
                <div className="space-y-4">
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 rounded-xl bg-red-accent/10 flex items-center justify-center">
                      <FileText size={20} className="text-red-accent" />
                    </div>
                    <div>
                      <p className="text-[14px] font-bold text-foreground">Speeda-Weekly-Report-March-2026.pdf</p>
                      <p className="text-[12px] text-muted-foreground">~1.2 MB</p>
                    </div>
                  </div>
                  <div className="flex gap-3">
                    <button onClick={handleDownload} className="flex-1 h-12 rounded-2xl gradient-btn text-primary-foreground font-bold text-[14px] shadow-btn btn-press flex items-center justify-center gap-2">
                      <Download size={16} /> Download PDF
                    </button>
                    <button onClick={() => { toast.success('Link copied ✓'); setExportStep('idle'); }} className="h-12 px-4 rounded-2xl border border-border text-foreground font-medium btn-press">
                      <Copy size={16} />
                    </button>
                  </div>
                  <div className="flex gap-2">
                    <button onClick={() => { toast.success('Shared via email ✓'); setExportStep('idle'); }} className="flex-1 h-10 rounded-xl border border-border text-foreground text-[12px] font-medium flex items-center justify-center gap-1.5">
                      <Mail size={14} /> Email
                    </button>
                    <button onClick={() => { toast.success('Link copied ✓'); setExportStep('idle'); }} className="flex-1 h-10 rounded-xl border border-border text-foreground text-[12px] font-medium flex items-center justify-center gap-1.5">
                      <Link2 size={14} /> Copy Link
                    </button>
                  </div>
                </div>
              )}
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </motion.div>
  );
};
